name: canvas-trmnl
region: sfo
services:
    - name: app
      github:
          repo: JoshuaBrest/canvas-trmnl
          branch: main
          deploy_on_push: true
      dockerfile_path: ./Dockerfile
      envs:
          - key: NODE_ENV
            value: production
          - key: PORT
            value: "3000"
            type: GENERAL
      instance_count: 1
      http_port: 3000
jobs:
    - name: migrate
      kind: PRE_DEPLOY
      github:
          repo: JoshuaBrest/canvas-trmnl
          branch: main
          deploy_on_push: true
      envs:
          - key: NODE_ENV
            value: production
            type: GENERAL
      dockerfile_path: ./migrate.dockerfile
    - name: job
      kind: POST_DEPLOY
      github:
          repo: JoshuaBrest/canvas-trmnl
          branch: main
          deploy_on_push: true
      envs:
          - key: NODE_ENV
            value: production
            type: GENERAL
      dockerfile_path: ./job.dockerfile
